### PR TITLE
Add job_function_name to POST uri for debugging

### PR DESCRIPTION
**Pull request by ghost**
This commit improves visibility into running jobs. The use-case we have in mind for this commit entails jobs that dominate workers. By appending the job_function_name to the URL, we can tell from logs what jobs may be overloading apache.

I intentionally did not use `std::string` here in order to avoid dynamic memory allocation, as the `processJob` function is marked `noexcept`. The workaround was to use a statically allocated buffer sized large enough to hold the URL + GET parameter.

I am passing the unit tests, but so far have not run this against apache.

### CODE REVIEW

**Comment by keyurdg** [comment]
Thanks for the PR @Zintinio! 

Given the URL is user inputted in the config, we'd need to parse it to append another query string to it, otherwise it can become mangled if it already contains a query param; it seems there's a boost library to parse and make URLs: https://github.com/cpp-netlib/uri

The parsing can be done in the constructor and then append as needed before the curl call.

**Review by keyurdg — CHANGES_REQUESTED** [review]
Thanks for the PR @Zintinio. Given that the `m_http_uri` is user input via the config, we'd need to append the new query param more carefully. I'd suggest using a URI parser (https://github.com/cpp-netlib/uri is a proposed standard and part of boost) in the constructor to break apart `m_http_uri` in the constructor of `GearmanClient`, and appending a new query param right before the curl call.

**Comment by ghost** [comment]
That's fair, my solution was a bit of a hack. I had overlooked the fact that the supplied URI was read in via config. I'll give it another shot with `boost::network::uri`.

**Comment by ghost** [comment]
Ok so some good news! I got this working with `network::uri`. Bad news: since my cmake-foo is not so strong I am having trouble loading the correct `.so`. I make a Cmake file and modified the build, but did not correctly link. ldd claims:

```
	linux-vdso.so.1 (0x00007ffc0be2a000)
	liblog4cxx.so.10 => /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10 (0x00007fd572788000)
	libnetwork-uri.so => not found

```

However! With an `LD_PRELOAD` hack the tests pass. So...I will be opening a second PR.

Also network::uri is not part of boost sadly. So I had to clone and build.

**Pull request closed without merging**
